additional_commands:
  nrn_add_test_group:
    pargs: 0
    kwargs:
      CORENEURON: 0
      ENVIRONMENT: '+'
      NAME: 1
      MODFILE_PATTERNS: '+'
      NRNIVMODL_ARGS: '+'
      OUTPUT: '+'
      SCRIPT_PATTERNS: '+'
      SIM_DIRECTORY: 1
      SUBMODULE: 1
  nrn_add_test:
    pargs: '+' # otherwise nrn_add_test(${add_test_args}) kills cmake-format
    kwargs:
      GROUP: 1
      NAME: 1
      COMMAND: '+'
      ENVIRONMENT: '+'
      CONFLICTS: '+'
      PRECOMMAND: '+'
      PRELOAD_SANITIZER: 0
      PROCESSORS: 1
      REQUIRES: '+'
      OUTPUT: '*'
      SCRIPT_PATTERNS: '*'
      SIM_DIRECTORY: '?'
  nrn_add_pytest:
    pargs: 0
    kwargs:
      GROUP: 1
      NAME: 1
      ENVIRONMENT: '+'
      MPI_RANKS: 1
      PYTEST_ARGS: '+'
      REQUIRES: '+'
      SCRIPT_PATTERNS: '*'
  nrn_add_test_group_comparison:
    pargs: 0
    kwargs:
      GROUP: 1
      REFERENCE_OUTPUT: '*'
  cpp_cc_build_time_copy:
    flags: ['NO_TARGET']
    kwargs:
      INPUT: '1'
      OUTPUT: '1'
  create_symlink:
    kwargs:
      NAME: '1'
      TARGET: '1'
